[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "openmpc"
version = "0.0.1"
authors = [
  { name="Mikael Johansson", email="mikaelj@kth.se" },
  { name="Pedro Roque", email="padr@kth.se" },
  { name="Gregorio Marchesini", email="gremar@kth.se" }
]
description = "Open source package for easy implementation of MPC control problems"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]

